import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="light"
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <head>
        <title>Your Application Name</title>
        <meta name="description" content="Your application description" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900 font-sans bg-white`}

        // className={`${inter.className} bg-gray-100`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Navbar */}

          {/* Main content area */}
          <div className="flex flex-1 flex-col md:flex-row overflow-hidden">
            {/* Sidebar for larger screens */}

            {/* Collapsible sidebar for smaller screens */}

            {/* Main content */}
            <main className="min-h-screen-patched bg-background flex w-full flex-col sm:flex-row">
            {/* <main className="flex-1 overflow-y-auto p-4 bg-white"> */}
              {children}
            </main>
          </div>

          {/* Footer */}
          <footer className="bg-white p-4 text-center text-sm shadow-t">
            &copy; {new Date().getFullYear()} Your Company Name. All rights
            reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
